name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL}}

    steps:
      - name: Check out code
        uses: actions/checkout@v4
      
      - name: Set up Goose
        uses: actions/setup-go@v5
        with:
          go-version: '1.20.x'

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"

      - name: Build Prod
        run: ./scripts/buildprod.sh

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
      
      - name: Use gcloud CLI
        run: gcloud info

      - name: Build and Push Docker image
        run: gcloud builds submit --tag asia-south1-docker.pkg.dev/notely-464811/notely-ar-repo/notely-app:latest

      - name: Database Migrations
        run: ./scripts/migrateup.sh

      - name: Deploy to Cloud Run
        run: gcloud run deploy notely --image asia-south1-docker.pkg.dev/notely-464811/notely-ar-repo/notely-app:latest --region asia-south1 --allow-unauthenticated --project notely-464811 --max-instances=4